export interface QuizQuestion {
  question: string;
  options: string[];
  correct: number; // index into options
  explanation: string;
  level: number;
}

export interface QuizCategory {
  name: string;
  questions: QuizQuestion[];
}

export const categories: QuizCategory[] = [
  {
    name: 'Fashion',
    questions: [
      // Level 1
      { question: 'What does "fast fashion" mean?', options: ['Clothing made slowly and carefully', 'Cheap clothes made quickly to follow trends', 'Handmade luxury clothing', 'Clothing designed to last 10+ years'], correct: 1, explanation: 'Fast fashion = fast production, low quality, disposable trends.', level: 1 },
      { question: 'Which material is most commonly used in fast fashion?', options: ['Polyester', 'Silk', 'Linen', 'Wool'], correct: 0, explanation: 'Polyester is cheap and easy to mass-produce, which is why fast fashion brands rely on it.', level: 1 },
      { question: 'True or False: Fast fashion is designed to be long-lasting.', options: ['True', 'False'], correct: 1, explanation: "It's intentionally low-quality so people buy more often.", level: 1 },
      { question: 'What is "overconsumption"?', options: ['Wearing the same clothes too often', 'Buying more clothes than you need', 'Donating too many clothes', 'Only buying second-hand'], correct: 1, explanation: 'Overconsumption = unnecessary purchasing → more waste.', level: 1 },
      { question: 'Which option is more sustainable?', options: ['Buying 3 cheap shirts', 'Buying 1 high-quality shirt', 'Buying clothes every week', 'Throwing clothes away after one use'], correct: 1, explanation: 'Durable clothing reduces replacement frequency and waste.', level: 1 },
      { question: 'What is a "microtrend"?', options: ['A long-lasting fashion movement', 'A trend that lasts only a few days or weeks', 'A trend created by luxury brands', 'A trend based on fabric thickness'], correct: 1, explanation: 'Microtrends burn out fast → more waste.', level: 1 },
      { question: 'Which of these is a sign of fast fashion?', options: ['High transparency reports', 'Weekly new collections', 'Long-lasting durable fabrics', 'Repair services'], correct: 1, explanation: 'Constant new drops encourage constant buying.', level: 1 },
      { question: 'What is the "real cost" of a cheap shirt?', options: ['Only the money you pay', 'Money + environmental + social impact', 'Only shipping costs', 'None'], correct: 1, explanation: 'The price tag hides pollution and worker exploitation.', level: 1 },
      // Level 2
      { question: 'What is the main driver of fast fashion pollution?', options: ['High prices', 'Slow production', 'High-volume manufacturing', 'Limited clothing drops'], correct: 2, explanation: 'Fast fashion produces too much, too fast.', level: 2 },
      { question: 'What makes polyester harmful?', options: ['It is fully biodegradable', 'It sheds microplastics', 'It is made from plants', 'It lasts for only one wash'], correct: 1, explanation: 'Polyester = plastic → microplastics in water.', level: 2 },
      { question: 'True or False: Cotton always has a lower environmental impact than polyester.', options: ['True', 'False'], correct: 1, explanation: 'Cotton can be better, but not always. It depends on method used.', level: 2 },
      { question: 'What is "greenwashing"?', options: ['A new eco-friendly washing technique', 'Misleading sustainability marketing', 'Washing clothes using recycled water', 'A method for dye removal'], correct: 1, explanation: 'Brands pretend to be sustainable without proof.', level: 2 },
      { question: 'Which fabric has the lowest water footprint?', options: ['Cotton', 'Linen', 'Wool', 'Nylon'], correct: 1, explanation: 'Linen (flax) uses far less water.', level: 2 },
      { question: 'Why do fast fashion prices stay low?', options: ['Brands use expensive materials', 'Very efficient, ethical labour', 'Cheap labour + cheap materials', 'Limited production'], correct: 2, explanation: 'Low cost = low wages + low-quality fibre.', level: 2 },
      { question: 'Which action reduces fashion waste the most?', options: ['Buying more clothes', 'Buying fewer, higher-quality clothes', 'Following microtrends', 'Wearing clothes once'], correct: 1, explanation: 'Longevity = fewer garments produced.', level: 2 },
      { question: 'What is the biggest issue with rapid fashion cycles?', options: ['They increase creativity', 'They reduce demand', 'They encourage disposable buying', 'They make clothes more durable'], correct: 2, explanation: 'Fast cycles → constant buying → waste.', level: 2 },
      // Level 3
      { question: 'Rank fabrics from worst → best environmental impact.', options: ['Linen → Wool → Polyester', 'Polyester → Cotton → Linen', 'Cotton → Polyester → Linen', 'Wool → Polyester → Cotton'], correct: 1, explanation: 'Polyester (plastic, energy-heavy) → Cotton (water-heavy) → Linen (lowest footprint).', level: 3 },
      { question: "Why don't clothing prices reflect environmental impact?", options: ['Because pollution is measured incorrectly', "Externalities aren't included in price", 'Because brands want to overcharge', 'Because fashion has no impact'], correct: 1, explanation: "Pollution isn't priced → artificially cheap clothes.", level: 3 },
      { question: 'What is "planned obsolescence" in fashion?', options: ['Designing clothes that last decades', 'Designing clothes that break or become unfashionable quickly', 'Designing for repairs', 'Designing clothing for upcycling'], correct: 1, explanation: 'Brands make products intentionally short-lived.', level: 3 },
      { question: 'Why is organic cotton not always more sustainable?', options: ['It uses more chemicals', 'It uses land and water differently', 'It cannot be dyed', 'It lasts fewer washes'], correct: 1, explanation: "Organic doesn't mean low water-use or efficient farming.", level: 3 },
      { question: 'What policy would reduce fashion waste most effectively?', options: ['More trend cycles', 'Banning second-hand clothing', 'Taxing high-waste production', 'Increasing billboard ads'], correct: 2, explanation: 'Pricing externalities reduces overproduction.', level: 3 },
      { question: 'What is "cost per wear"?', options: ['Price divided by number of wears', 'Total price multiplied by ownership time', 'Price divided by brand name', 'Cost of repairing clothes'], correct: 0, explanation: 'Lower cost-per-wear = more sustainable value.', level: 3 },
      { question: 'Why is relying on recycled polyester limited?', options: ['It cannot be recycled again', 'It is too expensive', 'It releases no microplastics', 'It is naturally biodegradable'], correct: 0, explanation: 'Most recycled polyester becomes non-recyclable clothing → dead-end.', level: 3 },
      { question: 'Which factor increases sustainability the most?', options: ['More trend cycles', 'Higher purchasing frequency', 'Longer product lifespans', 'More polyester production'], correct: 2, explanation: 'Longevity reduces overall consumption + waste.', level: 3 }
    ]
  },
  {
    name: 'Circular Economy',
    questions: [
      // Level 1
      { question: 'What is a circular economy?', options: ['An economy based on throwing items away', 'An economy where materials are reused, repaired, and recycled', 'An economy that only uses new materials', 'A system focused on fast production'], correct: 1, explanation: 'A circular economy keeps materials in use for as long as possible.', level: 1 },
      { question: 'Which diagram represents a linear economy?', options: ['Make → Use → Return', 'Take → Make → Waste', 'Repair → Reuse → Recycle', 'Collect → Process → Reuse'], correct: 1, explanation: 'A linear economy follows a one-way flow that ends in waste.', level: 1 },
      { question: 'True or False: Repairing an item is part of the circular economy.', options: ['True', 'False'], correct: 0, explanation: "Repair extends a product's life and reduces waste.", level: 1 },
      { question: 'What does "reuse" mean?', options: ['Throwing something away', 'Using a product again instead of buying new', 'Burning waste for energy', 'Replacing a broken item instantly'], correct: 1, explanation: 'Reuse keeps items circulating longer before disposal.', level: 1 },
      { question: 'What is upcycling?', options: ['Turning old materials into higher-value products', 'Burning materials', 'Recycling plastic into plastic', 'Throwing clothes away'], correct: 0, explanation: 'Upcycling transforms waste into something of higher value.', level: 1 },
      { question: 'What does "closing the loop" mean?', options: ['Ending recycling', 'Creating waste faster', 'Keeping materials in use instead of throwing them away', 'Stopping production permanently'], correct: 2, explanation: 'Closing the loop means resources continuously circulate.', level: 1 },
      { question: 'Which example fits a circular model?', options: ['Buying new clothes weekly', 'Repairing a broken bag', 'Throwing out old items', 'Ignoring waste'], correct: 1, explanation: 'Repairing prevents unnecessary new consumption.', level: 1 },
      { question: "Why is extending a product's life good for the environment?", options: ['It increases waste', 'It reduces production and resource use', 'It requires more material', 'It raises prices'], correct: 1, explanation: 'The longer an item lasts, the fewer new materials are needed.', level: 1 },
      // Level 2
      { question: 'Why is the linear economy unsustainable?', options: ['It reuses materials', 'It depends on infinite resources', 'It reduces waste naturally', 'It avoids pollution'], correct: 1, explanation: 'Linear systems rely on constant extraction from limited resources.', level: 2 },
      { question: 'What is "resource efficiency"?', options: ['Using as many materials as possible', 'Using materials in the smartest, most sustainable way', 'Throwing products away at the end of life', 'Over-consuming resources'], correct: 1, explanation: 'Efficient resource use reduces waste and environmental impact.', level: 2 },
      { question: 'True or False: Recycling is the only part of circularity.', options: ['True', 'False'], correct: 1, explanation: 'Circularity also includes reuse, repair, remanufacturing, and upcycling.', level: 2 },
      { question: 'Which company action reflects circular design?', options: ['Designing clothes meant to be thrown away', 'Using materials that can be repaired and recycled', 'Selling products with no repair options', 'Changing trends weekly'], correct: 1, explanation: 'Circular design focuses on durability and long-term usability.', level: 2 },
      { question: 'Which product is most likely to fit into a circular model?', options: ['A phone with glued-in batteries', 'A jacket with repairable zippers and modular parts', 'A shirt designed for one-time use', 'A plastic bag'], correct: 1, explanation: 'Modular and repairable items stay in use longer.', level: 2 },
      { question: 'How does upcycling reduce carbon emissions?', options: ['By increasing production', 'By reducing the need for new materials', 'By burning old products', 'By shortening product lifespan'], correct: 1, explanation: 'Using existing materials avoids the emissions from making new ones.', level: 2 },
      { question: 'What is "remanufacturing"?', options: ['Throwing away a product', 'Making a new item using old parts', 'Ignoring damaged materials', 'Always recycling first'], correct: 1, explanation: 'Remanufacturing gives parts a second life.', level: 2 },
      { question: 'Which strategy creates the least waste?', options: ['Reuse', 'Recycling', 'Repair', 'Burning waste'], correct: 2, explanation: 'Repair keeps products functional the longest.', level: 2 },
      // Level 3
      { question: 'How does circularity help fight climate change?', options: ['It increases consumption', 'It reduces extraction and production emissions', 'It causes more pollution', 'It promotes fast fashion'], correct: 1, explanation: 'Using fewer virgin materials lowers energy use and emissions.', level: 3 },
      { question: 'Which industry benefits most from circular innovation?', options: ['Nuclear energy', 'Textile and fashion', 'Luxury jewellery', 'Airline catering'], correct: 1, explanation: 'Textiles have massive waste and resource demands, so impact is huge.', level: 3 },
      { question: 'Which is the most effective circular strategy?', options: ['Recycling', 'Reuse', 'Repair', 'Refuse'], correct: 3, explanation: 'Refusing unnecessary items eliminates waste at the source.', level: 3 },
      { question: 'What makes a product "circular by design"?', options: ['It is trendy', "It's made to be repaired, reused, or recycled", 'It looks eco-friendly', 'It is cheap'], correct: 1, explanation: 'Circular-by-design products are built for multiple lifecycles.', level: 3 },
      { question: 'True or False: Recycling is the highest-impact circular solution.', options: ['True', 'False'], correct: 1, explanation: 'Recycling is useful, but less impactful than reducing, reusing, or repairing.', level: 3 },
      { question: 'Identify a major flaw in current circular systems.', options: ['Too much reuse', 'Lack of repair skills and infrastructure', 'Too many recycling options', 'Overproduction of circular products'], correct: 1, explanation: "Most people can't repair items, so products still get discarded.", level: 3 },
      { question: 'What is the difference between "cradle-to-grave" and "cradle-to-cradle"?', options: ['Same concept', 'Cradle-to-grave ends in waste; cradle-to-cradle recycles into new products', 'Cradle-to-grave recycles into new products; cradle-to-cradle ends in waste', 'Both ignore recycling'], correct: 1, explanation: 'Cradle-to-cradle is circular; cradle-to-grave is linear.', level: 3 },
      { question: 'A brand claims its product is circular but offers no repair options. What\'s the issue?', options: ["It's too sustainable", "It's greenwashing", "It's too expensive", "It's over-designed"], correct: 1, explanation: 'Circular claims must match real product features like durability and repairability.', level: 3 }
    ]
  },
  {
    name: 'Textile Lifecycle',
    questions: [
      // Level 1
      { question: "Which of these is the correct order of a textile lifecycle?", options: ['Use → Throw away → Production', 'Raw fibre → Fabric → Clothing → Use → Disposal', 'Disposal → Fabric → Raw fibre', 'Clothing → Fabric → Fibre'], correct: 1, explanation: 'A textile starts as raw fibre, becomes fabric, then clothing, is used, and eventually disposed of.', level: 1 },
      { question: "Which stage of a textile's life uses the most water?", options: ['Spinning', 'Dyeing', 'Transport', 'Packaging'], correct: 1, explanation: 'Dyeing and finishing processes use huge amounts of water.', level: 1 },
      { question: 'True or False: Dyeing is a major source of water pollution.', options: ['True', 'False'], correct: 0, explanation: 'Toxic dyes often enter rivers and ecosystems untreated.', level: 1 },
      { question: 'What happens to most discarded clothes globally?', options: ['They are recycled', 'They are stored forever', 'They end up in landfill or are burned', 'They turn into compost'], correct: 2, explanation: 'Most textile waste is landfilled or incinerated due to lack of recycling options.', level: 1 },
      { question: 'What is pre-consumer textile waste?', options: ['Clothes thrown away after wearing', 'Factory scraps and offcuts', 'Donated clothing', 'Old clothes sold second-hand'], correct: 1, explanation: 'Pre-consumer waste is created before the product reaches customers.', level: 1 },
      { question: 'What is post-consumer textile waste?', options: ['Scraps from textile factories', 'Unused fibres', 'Clothes discarded after use', 'Fabric rolls in storage'], correct: 2, explanation: 'Post-consumer waste = clothing thrown away after wearing.', level: 1 },
      { question: 'What part of the textile journey often involves the use of pesticides?', options: ['Spinning', 'Growing cotton', 'Sewing', 'Recycling'], correct: 1, explanation: 'Conventional cotton grows require pesticides and chemicals.', level: 1 },
      { question: 'True or False: Polyester sheds microplastics when washed.', options: ['True', 'False'], correct: 0, explanation: 'Synthetic fibres like polyester break into microplastics during washing.', level: 1 },
      // Level 2
      { question: 'Which stage of the textile lifecycle creates the most carbon emissions?', options: ['Sewing', 'Raw material production', 'Packaging', 'Retail'], correct: 1, explanation: 'Fibre production and processing typically have the highest carbon footprint.', level: 2 },
      { question: 'Why are polyester clothes hard to recycle?', options: ['They melt too quickly', 'They are often blended with other fibres', 'They are too soft', 'They are too expensive'], correct: 1, explanation: 'Blended fabrics make fibre separation extremely difficult.', level: 2 },
      { question: 'True or False: Blended fabrics are easier to reuse.', options: ['True', 'False'], correct: 1, explanation: 'Blends are harder to recycle and reuse due to mixed fibre content.', level: 2 },
      { question: 'What is a key environmental issue in the dyeing stage?', options: ['Fabric shrinkage', 'Wastewater pollution', 'Labour shortages', 'Slow production'], correct: 1, explanation: 'Dyeing creates toxic wastewater if not treated properly.', level: 2 },
      { question: "What is a textile's \"end-of-life\" stage?", options: ['The point at which it enters production', 'When it is sold', 'When it is discarded by the consumer', 'When cotton is harvested'], correct: 2, explanation: 'End-of-life refers to disposal after use.', level: 2 },
      { question: 'Why do clothes shed microplastics?', options: ['They contain natural fibres', 'Synthetic fibres break apart during friction', 'They are washed too often', 'They are recycled incorrectly'], correct: 1, explanation: 'Polyester and nylon release microplastics when stressed.', level: 2 },
      { question: 'Which stage is most labour-intensive?', options: ['Raw material extraction', 'Sewing and garment construction', 'Disposal', 'Recycling'], correct: 1, explanation: 'Cutting, sewing, and assembly rely heavily on manual labour.', level: 2 },
      { question: 'Which stage contributes most to chemical pollution?', options: ['Spinning', 'Dyeing & finishing', 'Retail', 'Transport'], correct: 1, explanation: 'Dyeing uses chemicals that can leak into ecosystems.', level: 2 },
      // Level 3
      { question: 'Why is textile recycling often inefficient?', options: ['Fabrics are too clean', 'Fibres are hard to separate, especially blends', 'No demand for recycled materials', 'It requires too much land'], correct: 1, explanation: 'Mixed fibres make automated sorting extremely difficult.', level: 3 },
      { question: 'Which fibre generally has the lowest environmental impact across its lifecycle?', options: ['Conventional cotton', 'Polyester', 'Linen (flax)', 'Nylon'], correct: 2, explanation: 'Linen uses less water and chemicals compared to other fibres.', level: 3 },
      { question: 'True or False: Mechanical recycling shortens fibre length.', options: ['True', 'False'], correct: 0, explanation: 'Shredding breaks fibres, reducing quality.', level: 3 },
      { question: 'What is a major barrier to large-scale textile recycling?', options: ['Too many recycling plants', 'Lack of sorting technology', 'Overproduction of linen', 'Low clothing demand'], correct: 1, explanation: 'Sorting blends and colours is complex and expensive.', level: 3 },
      { question: 'Which stage has the largest hidden environmental footprint?', options: ['Retail', 'Transport', 'Consumer use (washing, drying)', 'Sewing'], correct: 2, explanation: 'Frequent washing, drying, and ironing use huge amounts of energy.', level: 3 },
      { question: 'What makes chemical recycling different from mechanical recycling?', options: ['It dyes fibres', 'It dissolves fibres and rebuilds them as new', 'It cuts fibres into yarn', 'It burns waste'], correct: 1, explanation: 'Chemical recycling breaks fibres down molecularly.', level: 3 },
      { question: 'Why do darker dyed fabrics generally have a higher environmental impact?', options: ['They are more expensive', 'They require more dye and chemicals', 'They dry slower', 'They sell less'], correct: 1, explanation: 'Deep colours need more dye, increasing water and chemical use.', level: 3 },
      { question: 'What is the main issue with "fast fashion lifecycle speed"?', options: ['Clothes last too long', 'Clothes become waste too quickly', 'Recycling rates are too high', 'Clothes never get worn'], correct: 1, explanation: 'Fast fashion speeds up the path from production → disposal.', level: 3 }
    ]
  },
  {
    name: 'Sustainable Brands',
    questions: [
      // Level 1
      { question: 'What makes a brand "sustainable"?', options: ['Selling trendy clothes', 'Using materials and practices that reduce environmental harm', 'Releasing new collections every week', 'Only selling expensive items'], correct: 1, explanation: 'Sustainability = reduced environmental impact + ethical practices.', level: 1 },
      { question: 'True or False: An eco-label always means a brand is sustainable.', options: ['True', 'False'], correct: 1, explanation: 'Some labels can be misleading or unverified.', level: 1 },
      { question: 'Which of the following is a legitimate sustainability certification?', options: ['UltraGreen+', 'GOTS', 'FashionStar Label', 'EcoXPress'], correct: 1, explanation: 'GOTS is a globally trusted organic textile certification.', level: 1 },
      { question: 'What is "greenwashing"?', options: ['Washing clothes with eco-friendly soap', 'Making products green', 'Misleading consumers with fake sustainability claims', 'Dyeing clothes green'], correct: 2, explanation: 'Greenwashing = false or exaggerated eco-claims.', level: 1 },
      { question: 'What does "ethical sourcing" mean?', options: ['All materials come from expensive suppliers', 'Workers are paid fairly and materials are responsibly produced', 'Products are sourced from influencers', 'Items are sourced as fast as possible'], correct: 1, explanation: 'Ethical sourcing protects workers and the environment.', level: 1 },
      { question: 'Which brand behaviour is most likely sustainable?', options: ['No information about their supply chain', 'Extremely low prices', 'Publishing detailed sustainability reports', 'Releasing 50 collections per year'], correct: 2, explanation: 'Transparency is key to sustainability.', level: 1 },
      { question: 'Why do some sustainable brands cost more?', options: ['They want higher profits', 'They use higher-quality materials and pay fair wages', 'They avoid competition', 'They produce small sizes only'], correct: 1, explanation: 'Ethical labour + sustainable materials raise production costs.', level: 1 },
      { question: 'A brand advertises "eco-friendly" clothing but provides no proof. What is this?', options: ['Good marketing', 'Product innovation', 'Greenwashing', 'A new business model'], correct: 2, explanation: 'Unverified claims = classic greenwashing.', level: 1 },
      // Level 2
      { question: 'What does "supply chain transparency" mean?', options: ['Hiding production details', 'Showing where materials come from and how products are made', 'Revealing secret marketing plans', 'Shortening shipping times'], correct: 1, explanation: 'Transparency helps consumers verify sustainability.', level: 2 },
      { question: 'Why might a brand track its carbon footprint?', options: ['To raise prices', 'To understand and reduce its environmental impact', 'To impress customers only', 'To calculate shipping delays'], correct: 1, explanation: 'Measuring emissions helps identify reduction opportunities.', level: 2 },
      { question: 'True or False: A brand can still be sustainable if it uses plastic sometimes.', options: ['True', 'False'], correct: 0, explanation: 'Sustainability depends on total impact, not single materials.', level: 2 },
      { question: 'Which is a sign that a sustainability claim may be false?', options: ['Detailed data', 'Independent verification', 'Vague phrases like "100% eco-friendly"', 'Transparency reports'], correct: 2, explanation: 'Vague, unverified buzzwords are red flags.', level: 2 },
      { question: 'What is "circular fashion retail"?', options: ['Selling only circular-shaped clothing', 'Reselling, repairing, and renting clothing', 'Selling clothes in a circle arrangement', 'Only selling sustainable colours'], correct: 1, explanation: 'Circular retail extends clothing lifespan and reduces waste.', level: 2 },
      { question: 'What is the purpose of sustainability reporting?', options: ['To list celebrity collaborations', 'To brag about profits', 'To show impact metrics and accountability', 'To hide supply chain issues'], correct: 2, explanation: 'Sustainability reports show progress and areas for improvement.', level: 2 },
      { question: "Which metric matters most when judging a brand's sustainability?", options: ['Number of Instagram followers', 'How often they release new trends', 'Carbon footprint, water use, labour conditions', 'Colour of the logo'], correct: 2, explanation: 'Real sustainability = measurable environmental + social impact.', level: 2 },
      { question: 'Why is traceability important?', options: ['It helps track a product from source to consumer', 'It reduces brand popularity', 'It increases advertising opportunities', 'It makes trends last longer'], correct: 0, explanation: 'Traceability ensures materials and labour meet ethical standards.', level: 2 },
      // Level 3
      { question: 'A brand claims its clothing is "100% sustainable," but offers no data. What does this indicate?', options: ['Complete honesty', 'Likely greenwashing', 'A new marketing style', 'High product durability'], correct: 1, explanation: 'Absolute claims with no evidence are misleading.', level: 3 },
      { question: 'What is the difference between ESG and sustainability?', options: ['ESG focuses on financial markets; sustainability focuses on environmental & social impact', 'They are the same', 'ESG only deals with energy', 'Sustainability only deals with profits'], correct: 0, explanation: 'ESG evaluates companies for investors; sustainability focuses on real-world impact.', level: 3 },
      { question: 'What makes a sustainability strategy "scalable"?', options: ['It works only in small shops', 'It can expand across supply chains and locations', 'It is extremely expensive', 'It only applies to luxury brands'], correct: 1, explanation: 'Scalability = ability to expand impact widely.', level: 3 },
      { question: 'A brand claims its products use recycled polyester. What\'s important to check?', options: ['Whether the colours are trendy', 'Whether the recycled material is traceable and actually reduces impact', 'Whether influencers promote it', 'Whether the brand has good packaging'], correct: 1, explanation: 'Recycled claims must be verified and meaningful.', level: 3 },
      { question: 'True or False: Offsetting emissions alone makes a brand sustainable.', options: ['True', 'False'], correct: 1, explanation: 'Offsetting does not replace real reductions in emissions or waste.', level: 3 },
      { question: 'A brand says "sustainably sourced materials," but investigations show worker abuse in their factories. What is this?', options: ['High efficiency', 'Greenwashing', 'Successful sustainability', 'Carbon neutrality'], correct: 1, explanation: 'Sustainability includes labour rights, not just materials.', level: 3 },
      { question: 'Which approach gives the most accurate sustainability evaluation?', options: ['Marketing slogans', 'Third-party certifications + detailed impact data', 'Influencer partnerships', 'Fast trend cycles'], correct: 1, explanation: 'Independent verification prevents misleading claims.', level: 3 },
      { question: 'A company uses recycled materials but still overproduces clothing. What\'s the issue?', options: ['Recycled materials are harmful', 'Overproduction still causes massive waste', 'Recycled fibres never work', 'The clothes are too durable'], correct: 1, explanation: 'Sustainability requires reducing production volume, not just changing materials.', level: 3 }
    ]
  },
  {
    name: 'Recycling',
    questions: [
      // Level 1
      { question: 'What is recycling?', options: ['Throwing items away', 'Turning waste materials into new materials', 'Burning waste for energy', 'Washing items with water'], correct: 1, explanation: 'Recycling transforms used materials so they can be reused again.', level: 1 },
      { question: 'True or False: All fabrics can be recycled easily.', options: ['True', 'False'], correct: 1, explanation: 'Many fabrics, especially blends, are difficult or impossible to recycle.', level: 1 },
      { question: 'Why are blended fabrics hard to recycle?', options: ['They are too colourful', 'The fibres are mixed and hard to separate', 'They smell too much', 'They are too soft'], correct: 1, explanation: 'Separating fibres like cotton/polyester is technically challenging.', level: 1 },
      { question: 'What is "downcycling"?', options: ['Turning materials into higher-value products', 'Turning materials into lower-value products', 'Burning textiles', 'Reusing clothes'], correct: 1, explanation: 'Downcycling reduces material quality (e.g., clothes → insulation).', level: 1 },
      { question: 'What is contamination in recycling?', options: ['When waste is clean', 'When recycling bins are mixed with non-recyclables', 'When recycling is too efficient', 'When items are washed'], correct: 1, explanation: 'Contamination makes recycling less effective or impossible.', level: 1 },
      { question: 'True or False: Colour affects how easy it is to recycle textiles.', options: ['True', 'False'], correct: 0, explanation: 'Dark or mixed colours require more chemicals to process.', level: 1 },
      { question: 'What is closed-loop recycling?', options: ['Reusing materials until they degrade into waste', 'Recycling a material back into the same type of product', 'Burning materials for heat', 'Shredding materials into dust'], correct: 1, explanation: 'Closed-loop systems create new versions of the original product.', level: 1 },
      { question: 'Which of these is most commonly recycled in textiles?', options: ['Pure polyester', 'Polyester–cotton blends', 'Wool–nylon blends', 'Leather'], correct: 0, explanation: 'Pure polyester is easier to process than blends.', level: 1 },
      // Level 2
      { question: 'Which textile is easiest to mechanically recycle?', options: ['100% cotton', 'Cotton-polyester blend', 'Spandex', 'Leather'], correct: 0, explanation: 'Pure fibres recycle more smoothly than mixed ones.', level: 2 },
      { question: 'Why does polyester need heat during recycling?', options: ['To dye it', 'To melt and reshape it', 'To wash it', 'To make it softer'], correct: 1, explanation: 'Polyester is a plastic that must be melted to be reprocessed.', level: 2 },
      { question: 'True or False: Cotton can be mechanically recycled.', options: ['True', 'False'], correct: 0, explanation: 'Cotton can be shredded into shorter fibres for reuse.', level: 2 },
      { question: 'Which items should be donated rather than recycled?', options: ['Torn clothing', 'New or lightly used clothing', 'Wet clothing', 'Contaminated fabric'], correct: 1, explanation: 'High-quality items should be reused, not broken down.', level: 2 },
      { question: 'Why do many recycling markets collapse?', options: ['Too few recycling centres', 'No demand for recycled materials', 'Recycled products are too durable', 'Consumers recycle too much'], correct: 1, explanation: 'Recycling only works when buyers need the recycled output.', level: 2 },
      { question: 'What is a major difference between mechanical and chemical recycling?', options: ['Chemical recycling breaks fibres down into their basic molecules', 'Mechanical recycling dyes fabrics', 'Chemical recycling is always eco-friendly', 'Mechanical recycling strengthens fibres'], correct: 0, explanation: 'Chemical recycling molecularly rebuilds fibres.', level: 2 },
      { question: 'Which is more energy-efficient?', options: ['Producing new polyester', 'Recycling polyester', 'Burning polyester', 'Mining polyester'], correct: 1, explanation: 'Recycling plastic-based fibres requires less energy than producing new ones.', level: 2 },
      { question: 'What is the biggest issue in textile recycling facilities?', options: ['Too many workers', 'Sorting materials correctly', 'Too few clothes', 'Too much technology'], correct: 1, explanation: 'Sorting fabrics by fibre, colour, and quality is extremely difficult.', level: 2 },
      // Level 3
      { question: 'Why is textile recycling not widely scaled?', options: ["Consumers don't buy enough clothes", "Sorting technology is expensive and not advanced enough", 'Recycling takes too little time', 'Recycling is too profitable'], correct: 1, explanation: 'Sorting blends and colours is costly and complex.', level: 3 },
      { question: 'Which recycling method results in the highest-quality output?', options: ['Mechanical recycling', 'Chemical recycling', 'Downcycling', 'Burning textiles'], correct: 1, explanation: 'Chemical recycling can rebuild fibres to near-virgin quality.', level: 3 },
      { question: 'True or False: Chemical recycling is always environmentally friendly.', options: ['True', 'False'], correct: 1, explanation: 'It can require heavy chemicals and high energy use.', level: 3 },
      { question: 'Which type of textile is the biggest barrier to large-scale recycling?', options: ['100% cotton', 'Wool', 'Cotton–polyester blends', 'Linen'], correct: 2, explanation: 'Blends are extremely hard to separate into pure fibres.', level: 3 },
      { question: 'Why does recycling alone not solve fashion waste?', options: ['Recycling is too fast', "It doesn't reduce overproduction", 'Recycled clothes are too strong', 'People dislike recycled materials'], correct: 1, explanation: "Recycling doesn't fix the root issue: producing too much.", level: 3 },
      { question: 'What determines how effective textile recycling is?', options: ['Fabric colour only', 'Fibre purity, contamination, and sorting accuracy', 'Brand popularity', 'Garment size'], correct: 1, explanation: 'Pure fibres recycle best; contamination lowers recyclability.', level: 3 },
      { question: 'Which factor most limits fibre recovery rates?', options: ['Number of trends', 'Damage to fibres during mechanical recycling', 'Popularity of thrifting', 'Fabric colour'], correct: 1, explanation: 'Mechanical recycling shortens fibres, reducing quality.', level: 3 },
      { question: 'What is the biggest weakness of downcycling long-term?', options: ['It makes clothes too expensive', 'Materials eventually become unusable and still end up as waste', 'It creates too much profit', 'It makes fibres too strong'], correct: 1, explanation: 'Downcycling delays waste but does not create a closed loop.', level: 3 }
    ]
  },
  {
    name: 'Sustainable Lifestyle',
    questions: [
      // Level 1
      { question: 'What does "living sustainably" mean?', options: ['Buying as many new products as possible', 'Making choices that reduce environmental impact', 'Only purchasing luxury items', 'Living without electricity'], correct: 1, explanation: 'Sustainability is about reducing harm to the planet.', level: 1 },
      { question: 'True or False: Washing clothes less often can reduce environmental impact.', options: ['True', 'False'], correct: 0, explanation: 'Laundry uses water, energy, and sheds microplastics.', level: 1 },
      { question: 'What is a simple way to reduce microplastic pollution?', options: ['Washing clothes at high temperatures', 'Washing synthetic clothes less often', 'Buying only dark clothes', 'Throwing clothes away quicker'], correct: 1, explanation: 'Less washing = fewer microplastics released.', level: 1 },
      { question: 'What is mindful consumption?', options: ['Buying clothes without thinking', 'Buying only what you truly need', 'Buying anything on sale', 'Shopping every weekend'], correct: 1, explanation: "It's about intentional, reduced consumption.", level: 1 },
      { question: 'Which of these habits is sustainable?', options: ['Air-drying clothes', 'Using the dryer for every load', 'Buying new clothes weekly', 'Throwing away repairable items'], correct: 0, explanation: 'Air-drying cuts energy use significantly.', level: 1 },
      { question: 'Why is repairing clothes better than replacing them?', options: ['It is always cheaper', 'It reduces waste and avoids new production', 'It makes clothes look brand new', 'It increases fashion trends'], correct: 1, explanation: "Repairing extends a garment's life and avoids new emissions.", level: 1 },
      { question: 'True or False: Individual actions make no difference in sustainability.', options: ['True', 'False'], correct: 1, explanation: 'Small actions add up, especially at scale.', level: 1 },
      { question: 'What is a carbon footprint?', options: ['A shoe print', 'Total greenhouse gases a person or activity produces', 'A type of recycled fabric', 'A clothing style'], correct: 1, explanation: 'It measures climate impact from daily choices.', level: 1 },
      // Level 2
      { question: 'What is one way to lower your clothing-related carbon footprint?', options: ['Buy clothes frequently', 'Wash clothes in cold water', 'Throw clothes out after one use', 'Wash everything at 90\u00b0C'], correct: 1, explanation: 'Cold washing reduces energy use dramatically.', level: 2 },
      { question: 'Which pattern of shopping is most sustainable?', options: ['Buying fewer, high-quality clothes', 'Buying fast fashion weekly', 'Buying based on trends only', 'Buying only discounted items'], correct: 0, explanation: 'Durability reduces overconsumption and waste.', level: 2 },
      { question: 'True or False: Air drying clothes is more sustainable than using a dryer.', options: ['True', 'False'], correct: 0, explanation: 'Dryers use lots of electricity; air drying uses none.', level: 2 },
      { question: 'What is one way to reduce waste at home?', options: ['Using disposable items', 'Choosing reusable products', 'Buying unnecessary items', 'Using plastic bags frequently'], correct: 1, explanation: 'Reusable items cut waste significantly.', level: 2 },
      { question: 'What daily habit reduces water use?', options: ['Washing clothes after every wear', 'Taking shorter showers', 'Leaving the tap running', 'Washing synthetic clothes daily'], correct: 1, explanation: 'Shorter showers save water instantly.', level: 2 },
      { question: 'What is the problem with "eco-friendly" trends?', options: ['They last forever', 'They often encourage buying more', 'They save too much energy', 'They reduce brand profits'], correct: 1, explanation: 'Overconsumption is still harmful even if items are "eco".', level: 2 },
      { question: 'Which choice is better for the environment?', options: ['Throwing away old clothes', 'Donating or reselling clothes', 'Buying duplicates', 'Buying only synthetic fabrics'], correct: 1, explanation: 'Reuse extends the life of garments.', level: 2 },
      { question: 'Why do sustainable habits matter long-term?', options: ['They save time', 'They compound — small habits create large impact', 'They eliminate all emissions instantly', 'They make clothes last forever'], correct: 1, explanation: 'Consistent habits add up to major environmental savings.', level: 2 },
      // Level 3
      { question: 'Which lifestyle change has the highest environmental impact?', options: ['Buying new clothes monthly', 'Reducing overall consumption', 'Washing synthetic clothes more often', 'Air-drying only'], correct: 1, explanation: 'Reducing consumption cuts emissions, waste, and resource use.', level: 3 },
      { question: 'Why is "buying eco-friendly items" not always sustainable?', options: ["Eco-items don't work", 'It still encourages consumption', 'They are illegal', 'They last too long'], correct: 1, explanation: "The most sustainable item is the one you don't buy.", level: 3 },
      { question: 'True or False: Microplastic pollution only comes from oceans.', options: ['True', 'False'], correct: 1, explanation: 'Most microplastics come from washing clothes and daily activities.', level: 3 },
      { question: 'What is a realistic long-term sustainable goal?', options: ['Never buying clothes again', 'Slowly shifting to durable, repairable items', 'Throwing away everything synthetic', 'Buying only luxury brands'], correct: 1, explanation: 'Sustainable transitions happen gradually and practically.', level: 3 },
      { question: 'Which action reduces waste the MOST?', options: ['Recycling everything', 'Avoiding unnecessary purchases', 'Washing clothes in hot water', 'Buying duplicates'], correct: 1, explanation: 'Avoiding waste at the source is the highest-impact solution.', level: 3 },
      { question: 'What is a "waste footprint"?', options: ['Trash left on the ground', 'Total waste an individual or household produces', 'Footprint size', 'The amount a person recycles'], correct: 1, explanation: 'It tracks how much waste you generate overall.', level: 3 },
      { question: 'Which is a common mistake in attempting sustainable living?', options: ['Repairing items', 'Buying excess "eco-friendly" products', 'Reducing consumption', 'Using fewer resources'], correct: 1, explanation: 'Buying too many "eco" items still leads to unnecessary waste.', level: 3 },
      { question: 'Why do lifestyle changes need to be maintained consistently?', options: ["One-time actions don't create lasting environmental impact", 'Sustainability is only about trends', 'Governments require it', 'It is expensive otherwise'], correct: 0, explanation: 'Long-term behaviour creates long-term environmental benefits.', level: 3 }
    ]
  }
];
